// GARAGE 70/80 — данные каталога

const COUNTRIES = {
  usa: { id: 'usa', name: 'США', flag: '🇺🇸', color: '#cc3333' },
  japan: { id: 'japan', name: 'Япония', flag: '🇯🇵', color: '#d4af37' },
  germany: { id: 'germany', name: 'Германия', flag: '🇩🇪', color: '#4a7fc4' },
};

const CLASSES = {
  muscle: { id: 'muscle', name: 'Маслкар', shape: 'sport' },
  sports: { id: 'sports', name: 'Спорткар', shape: 'sport' },
  coupe: { id: 'coupe', name: 'Купе', shape: 'coupe' },
  sedan: { id: 'sedan', name: 'Седан', shape: 'sedan' },
  compact: { id: 'compact', name: 'Компакт', shape: 'compact' },
  luxury: { id: 'luxury', name: 'Люкс', shape: 'luxury' },
  suv: { id: 'suv', name: 'Внедорожник', shape: 'suv' },
};

const CARS = [
  // ---------- США ----------
  {
    id: 'ford-mustang-mach1',
    name: 'Ford Mustang Mach 1',
    country: 'usa',
    classId: 'muscle',
    year: 1973,
    yearRange: '1971–1973',
    engine: '5.8 л V8 (351 Cleveland)',
    power: 156,
    torque: 407,
    accel: 9.8,
    topSpeed: 190,
    weight: 1595,
    drive: 'задний',
    price: '≈ $3 088',
    description: 'Флагманская спортивная версия Mustang третьего поколения с удлинённым капотом и характерным воздухозаборником Ram Air. К 1973 году мощность двигателей заметно упала из-за новых экологических норм, но силуэт остался узнаваемым символом эпохи.',
    bodyColor: '#d94f2b',
  },
  {
    id: 'chevrolet-camaro-z28',
    name: 'Chevrolet Camaro Z28',
    country: 'usa',
    classId: 'muscle',
    year: 1978,
    yearRange: '1977–1981',
    engine: '5.7 л V8 (350 L82)',
    power: 185,
    torque: 380,
    accel: 8.6,
    topSpeed: 200,
    weight: 1650,
    drive: 'задний',
    price: '≈ $5 600',
    description: 'Возрождение спортивного пакета Z28 после паузы конца 60-х. Жёсткая подвеска, широкие колёсные арки и агрессивная графика на кузове сделали модель одним из символов позднего маслкар-движения.',
    bodyColor: '#1c1c1c',
  },
  {
    id: 'pontiac-firebird-trans-am',
    name: 'Pontiac Firebird Trans Am',
    country: 'usa',
    classId: 'muscle',
    year: 1977,
    yearRange: '1976–1978',
    engine: '6.6 л V8 (400 T/A 6.6)',
    power: 200,
    torque: 447,
    accel: 8.1,
    topSpeed: 205,
    weight: 1700,
    drive: 'задний',
    price: '≈ $5 004',
    description: 'Прославился благодаря фильму «Смоки и Бандит» и фирменному капоту с орлом «Screaming Chicken». Один из немногих маслкаров конца 70-х, сохранивших крупный V8 и внушительный крутящий момент.',
    bodyColor: '#101820',
  },
  {
    id: 'dodge-charger-se',
    name: 'Dodge Charger SE',
    country: 'usa',
    classId: 'coupe',
    year: 1975,
    yearRange: '1975–1978',
    engine: '5.9 л V8 (360)',
    power: 175,
    torque: 365,
    accel: 10.5,
    topSpeed: 175,
    weight: 1800,
    drive: 'задний',
    price: '≈ $4 700',
    description: 'Личное купе на платформе Chrysler Cordoba — более комфортное и премиальное, чем маслкары начала 70-х. Виниловая крыша и хромированная решётка подчёркивали статус модели.',
    bodyColor: '#8a1f1f',
  },
  {
    id: 'chevrolet-corvette-c3',
    name: 'Chevrolet Corvette C3',
    country: 'usa',
    classId: 'sports',
    year: 1980,
    yearRange: '1968–1982',
    engine: '5.7 л V8 (350 L48)',
    power: 190,
    torque: 380,
    accel: 8.3,
    topSpeed: 200,
    weight: 1540,
    drive: 'задний',
    price: '≈ $13 140',
    description: 'Кузов «Coke Bottle» с выступающими арками и клиновидным профилем стал одним из самых узнаваемых силуэтов американского спорткара. К 1980 году получил обновлённый интерьер и облегчённую конструкцию.',
    bodyColor: '#c9a227',
  },
  {
    id: 'cadillac-eldorado',
    name: 'Cadillac Eldorado',
    country: 'usa',
    classId: 'luxury',
    year: 1976,
    yearRange: '1971–1978',
    engine: '8.2 л V8 (500 cui)',
    power: 190,
    torque: 481,
    accel: 11.5,
    topSpeed: 175,
    weight: 2200,
    drive: 'передний',
    price: '≈ $10 586',
    description: 'Один из крупнейших переднеприводных автомобилей в истории и последнее купе-кабриолет Америки перед временным запретом открытых кузовов. Символ роскоши эпохи «бархатной» Америки.',
    bodyColor: '#f5f0e6',
  },
  {
    id: 'lincoln-continental-mark-v',
    name: 'Lincoln Continental Mark V',
    country: 'usa',
    classId: 'luxury',
    year: 1977,
    yearRange: '1977–1979',
    engine: '6.6 л V8 (400)',
    power: 179,
    torque: 460,
    accel: 12.0,
    topSpeed: 170,
    weight: 2200,
    drive: 'задний',
    price: '≈ $11 315',
    description: 'Личный люксовый автомобиль с фальшивым запасным колесом на крышке багажника и «continental hump» — фирменной деталью линейки Continental Mark. Один из самых продаваемых люксовых купе своего времени.',
    bodyColor: '#3a3f4b',
  },
  {
    id: 'jeep-cj7',
    name: 'Jeep CJ-7',
    country: 'usa',
    classId: 'suv',
    year: 1979,
    yearRange: '1976–1986',
    engine: '4.2 л I6',
    power: 110,
    torque: 240,
    accel: 14.0,
    topSpeed: 130,
    weight: 1360,
    drive: 'полный',
    price: '≈ $5 300',
    description: 'Удлинённый преемник CJ-5 с увеличенной колёсной базой и опциональной автоматической коробкой. Один из первых по-настоящему универсальных внедорожников — для бездорожья и повседневной езды.',
    bodyColor: '#4f6b3a',
  },

  // ---------- Япония ----------
  {
    id: 'toyota-celica-gt',
    name: 'Toyota Celica GT',
    country: 'japan',
    classId: 'coupe',
    year: 1978,
    yearRange: '1977–1981',
    engine: '2.2 л I4',
    power: 96,
    torque: 172,
    accel: 11.5,
    topSpeed: 165,
    weight: 1080,
    drive: 'задний',
    price: '≈ $5 300',
    description: 'Второе поколение Celica переняло дизайнерские мотивы американских «пони-каров» — длинный капот и короткую заднюю часть. Доступный и надёжный спортивный купе для японского и экспортных рынков.',
    bodyColor: '#e2b93b',
  },
  {
    id: 'datsun-280z',
    name: 'Datsun 280Z (Fairlady Z)',
    country: 'japan',
    classId: 'sports',
    year: 1978,
    yearRange: '1975–1978',
    engine: '2.8 л I6',
    power: 149,
    torque: 220,
    accel: 9.5,
    topSpeed: 195,
    weight: 1250,
    drive: 'задний',
    price: '≈ $9 000',
    description: 'Флагман линейки Z с увеличенным до 2,8 литра двигателем и электронным впрыском топлива — ответ на ужесточение экологических норм в США. Один из самых продаваемых спорткаров десятилетия.',
    bodyColor: '#b5451b',
  },
  {
    id: 'mazda-rx7-sa22c',
    name: 'Mazda RX-7 (SA22C)',
    country: 'japan',
    classId: 'sports',
    year: 1979,
    yearRange: '1978–1985',
    engine: '1.1 л роторный (12A)',
    power: 100,
    torque: 138,
    accel: 9.2,
    topSpeed: 187,
    weight: 1035,
    drive: 'задний',
    price: '≈ $6 395',
    description: 'Компактный роторный двигатель Ванкеля позволил разместить силовой агрегат позади передней оси, добившись почти идеальной развесовки. Лёгкий, отзывчивый спорткар, ставший визитной карточкой Mazda.',
    bodyColor: '#c94b4b',
  },
  {
    id: 'honda-civic-cvcc',
    name: 'Honda Civic CVCC',
    country: 'japan',
    classId: 'compact',
    year: 1979,
    yearRange: '1975–1979',
    engine: '1.5 л I4',
    power: 68,
    torque: 113,
    accel: 14.5,
    topSpeed: 140,
    weight: 750,
    drive: 'передний',
    price: '≈ $3 650',
    description: 'Технология CVCC (Compound Vortex Controlled Combustion) позволила двигателю соответствовать жёстким нормам выбросов США без каталитического нейтрализатора. Символ экономичности в годы нефтяного кризиса.',
    bodyColor: '#e8823a',
  },
  {
    id: 'toyota-corolla-e30',
    name: 'Toyota Corolla E30',
    country: 'japan',
    classId: 'compact',
    year: 1979,
    yearRange: '1979–1983',
    engine: '1.6 л I4',
    power: 75,
    torque: 124,
    accel: 13.0,
    topSpeed: 150,
    weight: 900,
    drive: 'задний',
    price: '≈ $3 700',
    description: 'Четвёртое поколение Corolla — простой, недорогой и надёжный компакт, ставший одним из самых массовых автомобилей в мире. Заднеприводная компоновка сохранялась вплоть до следующего поколения.',
    bodyColor: '#d6d2c4',
  },
  {
    id: 'datsun-510',
    name: 'Datsun 510',
    country: 'japan',
    classId: 'sedan',
    year: 1973,
    yearRange: '1968–1973',
    engine: '1.6 л I4',
    power: 96,
    torque: 135,
    accel: 12.5,
    topSpeed: 160,
    weight: 950,
    drive: 'задний',
    price: '≈ $2 700',
    description: 'Недорогой седан с независимой подвеской и сбалансированной динамикой, за что получил прозвище «бюджетный BMW». Успешно выступал в ралли и кузовных гонках по всему миру.',
    bodyColor: '#3f6f8f',
  },
  {
    id: 'mitsubishi-galant-lambda',
    name: 'Mitsubishi Galant Lambda',
    country: 'japan',
    classId: 'sedan',
    year: 1980,
    yearRange: '1976–1980',
    engine: '2.0 л I4 турбо',
    power: 145,
    torque: 206,
    accel: 9.8,
    topSpeed: 190,
    weight: 1150,
    drive: 'задний',
    price: '≈ $7 200',
    description: 'Спортивное купе-седан с клиновидным силуэтом и одним из первых серийных турбомоторов в Японии. Ставил акцент на технологичность и динамику вместо роскоши.',
    bodyColor: '#7a3fa0',
  },
  {
    id: 'subaru-leone-4wd-estate',
    name: 'Subaru Leone 4WD Estate',
    country: 'japan',
    classId: 'suv',
    year: 1979,
    yearRange: '1979–1984',
    engine: '1.6 л I4',
    power: 67,
    torque: 118,
    accel: 15.0,
    topSpeed: 140,
    weight: 970,
    drive: 'полный',
    price: '≈ $5 700',
    description: 'Один из первых массовых легковых универсалов с постоянным полным приводом — предок современных subaru-платформ. Практичный выбор для сельской местности и заснеженных дорог.',
    bodyColor: '#5a7350',
  },

  // ---------- Германия ----------
  {
    id: 'bmw-30-csl',
    name: 'BMW 3.0 CSL',
    country: 'germany',
    classId: 'coupe',
    year: 1972,
    yearRange: '1971–1975',
    engine: '3.0 л I6',
    power: 200,
    torque: 280,
    accel: 7.3,
    topSpeed: 220,
    weight: 1270,
    drive: 'задний',
    price: '≈ $14 000',
    description: 'Облегчённая гомологационная версия купе E9 с алюминиевыми панелями кузова и культовым аэродинамическим обвесом «Batmobile». Доминировала в кузовных чемпионатах Европы 1970-х.',
    bodyColor: '#f2f2f2',
  },
  {
    id: 'bmw-m1',
    name: 'BMW M1',
    country: 'germany',
    classId: 'sports',
    year: 1978,
    yearRange: '1978–1981',
    engine: '3.5 л I6 (M88)',
    power: 277,
    torque: 330,
    accel: 5.6,
    topSpeed: 262,
    weight: 1300,
    drive: 'задний',
    price: '≈ $60 000',
    description: 'Первый и единственный среднемоторный суперкар BMW, созданный совместно с Lamborghini и Giugiaro. Заложил основу для будущего подразделения BMW M и серии гонок Procar.',
    bodyColor: '#c0392b',
  },
  {
    id: 'mercedes-450sl-r107',
    name: 'Mercedes-Benz 450 SL (R107)',
    country: 'germany',
    classId: 'sports',
    year: 1973,
    yearRange: '1971–1980',
    engine: '4.5 л V8',
    power: 225,
    torque: 375,
    accel: 9.5,
    topSpeed: 205,
    weight: 1600,
    drive: 'задний',
    price: '≈ $17 946',
    description: 'Родстер с двумя съёмными крышами и репутацией одного из самых надёжных люксовых спорткаров эпохи. Простоял в производстве почти два десятилетия почти без изменений во внешности.',
    bodyColor: '#9c1c1c',
  },
  {
    id: 'porsche-911-turbo-930',
    name: 'Porsche 911 Turbo (930)',
    country: 'germany',
    classId: 'sports',
    year: 1975,
    yearRange: '1975–1989',
    engine: '3.0 л турбо, оппозитный-6',
    power: 260,
    torque: 343,
    accel: 5.2,
    topSpeed: 250,
    weight: 1140,
    drive: 'задний',
    price: '≈ $26 000',
    description: 'Первый серийный турбированный 911 с характерным широким задним крылом «китовый хвост». Резкая турбояма на низких оборотах закрепила за моделью репутацию одного из самых требовательных суперкаров своего времени.',
    bodyColor: '#232323',
  },
  {
    id: 'vw-golf-gti-mk1',
    name: 'Volkswagen Golf GTI Mk1',
    country: 'germany',
    classId: 'compact',
    year: 1976,
    yearRange: '1976–1983',
    engine: '1.6 л I4',
    power: 110,
    torque: 140,
    accel: 9.0,
    topSpeed: 182,
    weight: 810,
    drive: 'передний',
    price: '≈ DM 13 850',
    description: 'Автомобиль, фактически придумавший категорию «горячий хэтч»: лёгкий кузов, впрыск топлива и характерная красная окантовка решётки радиатора. Изначально планировался как ограниченная серия для гомологации.',
    bodyColor: '#d6392a',
  },
  {
    id: 'audi-quattro',
    name: 'Audi Quattro',
    country: 'germany',
    classId: 'coupe',
    year: 1980,
    yearRange: '1980–1991',
    engine: '2.1 л турбо I5',
    power: 200,
    torque: 285,
    accel: 7.1,
    topSpeed: 220,
    weight: 1290,
    drive: 'полный',
    price: '≈ DM 49 900',
    description: 'Первый серийный спортивный автомобиль с постоянным полным приводом, перевернувший расстановку сил в ралли-чемпионатах группы B. Технология quattro определила облик Audi на десятилетия вперёд.',
    bodyColor: '#8a1414',
  },
  {
    id: 'mercedes-280e-w123',
    name: 'Mercedes-Benz 280E (W123)',
    country: 'germany',
    classId: 'sedan',
    year: 1976,
    yearRange: '1976–1985',
    engine: '2.8 л I6',
    power: 177,
    torque: 235,
    accel: 9.9,
    topSpeed: 195,
    weight: 1420,
    drive: 'задний',
    price: '≈ $14 000',
    description: 'Один из самых надёжных седанов в истории марки — простая и прочная конструкция сделала W123 популярным такси во многих странах Европы и Африки. Эталон инженерной сдержанности.',
    bodyColor: '#4a5866',
  },
  {
    id: 'opel-manta-gte',
    name: 'Opel Manta GT/E',
    country: 'germany',
    classId: 'coupe',
    year: 1975,
    yearRange: '1975–1988',
    engine: '1.9 л I4',
    power: 105,
    torque: 155,
    accel: 10.5,
    topSpeed: 178,
    weight: 990,
    drive: 'задний',
    price: '≈ DM 13 000',
    description: 'Доступное заднеприводное купе, конкурировавшее с Ford Capri. Версия GT/E получила впрыск топлива и спортивный обвес, снискав популярность в любительских кузовных гонках.',
    bodyColor: '#e0a92e',
  },
];

const MAX_POWER = Math.max(...CARS.map((c) => c.power));
const MAX_SPEED = 300; // шкала спидометра, км/ч
